#
# Your Crowdin credentials
#
project_id_env: &project_id CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
project_id: *project_id
base_path: "."
base_url: "https://api.crowdin.com"
#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true
#
# Files configuration
#
files:
  - source: CONDUCT.md
    dest: /%original_file_name%
    translation: /%file_name%-%locale%.%file_extension%
  - source: CONTRIBUTING.md
    dest: /%original_file_name%
    translation: /%file_name%-%locale%.%file_extension%
  - source: README.md
    dest: /%original_file_name%
    translation: /%file_name%-%locale%.%file_extension%
  - source: /book/**/*.md
    dest: /book/**/%original_file_name%
    translation: /book/%locale%/**/%original_file_name%
    ignore: [/book/%locale%/*.md]
