channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterhub-singleuser>=3.0,<4.0
  - jupyterlab
  - jupyter-book
  - jupyterlab-myst
  - jupyterlab-git
  - rasterio
  - numpy  
  - matplotlib
  - gdal
  - pystac-client
  - geopandas
  - basemap
  - jupytext
  - geoviews
  - rioxarray
  - contextily
  - ghp-import
  - gh-scoped-creds
  - nbgitpuller=1.1.*