name: climaterisk
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - rasterio
  - matplotlib
  - gdal
  - pystac-client
  - geopandas
  - basemap
  - jupytext
  - geoviews
  - rioxarray
  - contextily