channels:
  - conda-forge
  - pyviz
dependencies:
  - basemap
  - bokeh
  - boto3
  - contextily  
  - folium
  - fsspec  
  - gdal
  - geopandas
  - geoviews
  - geoviews-core
  - ghp-import
  - gh-scoped-creds  
  - h5py
  - holoviews
  - hvplot
  - imageio
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipython
  - jupyterlab
  - jupyter-book
  - jupyter-server-proxy>=4.1.1
  - jupyterlab-myst
  - jupyterlab-git
  - jupyterhub>=4.1.5
  - jupyterhub-singleuser
  - jupytext  
  - leafmap
  - localtileserver
  - lxml  
  - matplotlib
  - nbgitpuller>=1.2.1
  - nodejs
  - notebook
  - numba
  - numexpr>=2.8.7
  - numpy
  - panel
  - pystac-client
  - rasterio
  - requests
  - rioxarray
  - s3fs  
  - scikit-image  
  - selenium
  - xarray
