name: Update paths

on:
  push:
    paths:
      - '**/es-419'
      - '*-es-419.md'
    branches:
      - main
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  rename:
      runs-on: ubuntu-latest
      steps:
        - name: Rename locale to be more human-friendly
          run: |
            find . -depth -type d -name 'es-419' -execdir mv {} espanol \;
            find . -depth -name '*-es-419.md' -execdir bash -c 'mv -i "$1" "${1//es-419/es}"' bash {} \;

        - name: Commit changes
          run: |
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git commit -a -m 'Rename locale to be more human-friendly' || echo "No changes to commit"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
